name: admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # --- Gerekli Paketler (Tek ve Güncel Liste) ---
  provider: ^6.1.1
  http: ^1.2.0
  intl: ^0.19.0
  table_calendar: ^3.1.0
  flutter_secure_storage: ^9.0.0

  # İkonlar
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # --- Resim Klasörü Tanımlaması ---
  assets:
    - assets/images/