name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.8
  
  # Diğer Paketler
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  mask_text_input_formatter: ^2.9.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  
  # Senin eklemek istediklerin (Doğru yer burası)
  table_calendar: ^3.0.9
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true